image: ubuntu:18.04

before_script:
  - apt-get update && apt-get -y install make curl gnupg2

stages:
  - lint
  - test

web-frontend-eslint:
  stage: lint
  script:
    - make install-web-frontend-dependencies
    - make eslint-web-frontend

web-frontend-stylelint:
  stage: lint
  script:
    - make install-web-frontend-dependencies
    - make stylelint-web-frontend

web-frontend-test:
  stage: test
  script:
    - make install-web-frontend-dependencies
    - make test-web-frontend

backend-flake8:
  stage: lint
  image: python:3.6
  script:
    - make install-backend-dependencies
    - make lint-backend

backend-pytest:
  stage: test
  image: python:3.6
  services:
    - name: postgres:11.3
      alias: db
  variables:
    POSTGRES_USER: baserow
    POSTGRES_PASSWORD: baserow
    POSTGRES_DB: baserow
  script:
    - make install-backend-dependencies
    - export PYTHONPATH=$CI_PROJECT_DIR/backend/src
    - make test-backend
