before_script:
  - apt-get update && apt-get -y install make curl gnupg2

stages:
  - lint
  - test

web-frontend-eslint:
  stage: lint
  image: node:10
  script:
    - cd web-frontend
    - make install-dependencies
    - make eslint

web-frontend-stylelint:
  stage: lint
  image: node:10
  script:
    - cd web-frontend
    - make install-dependencies
    - make stylelint

web-frontend-test:
  stage: test
  image: node:10
  script:
    - cd web-frontend
    - make install-dependencies
    - make test

backend-flake8:
  stage: lint
  image: python:3.6
  script:
    - cd backend
    - make install-dependencies
    - make lint

backend-pytest:
  stage: test
  image: python:3.6
  services:
    - name: postgres:11.3
      alias: db
  variables:
    POSTGRES_USER: baserow
    POSTGRES_PASSWORD: baserow
    POSTGRES_DB: baserow
  script:
    - cd backend
    - make install-dependencies
    - export PYTHONPATH=$CI_PROJECT_DIR/backend/src
    - make test
