repos:
    -   repo: local
        hooks:
            -   id: frontend-lint
                name: frontend lint
                language: system
                entry: bash -c 'docker-compose run --no-deps web-frontend make lint'
                pass_filenames: false
                files: ^web-frontend/
    -   repo: local
        hooks:
            -   id: backend-lint
                name: backend lint
                language: system
                entry: bash -c 'docker-compose run --no-deps backend make lint'
                pass_filenames: false
                files: ^backend/
