version: "3"

services:
  db:
    container_name: db
    image: postgres:11.3
    environment:
      - POSTGRES_USER=baserow
      - POSTGRES_PASSWORD=baserow
      - POSTGRES_DB=baserow
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  mjml:
    container_name: mjml
    image: liminspace/mjml-tcpserver:latest
    ports:
      - 28101:28101

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=baserow
      - POSTGRES_PASSWORD=baserow
      - POSTGRES_DB=baserow
      - DATABASE_PORT=5432
      - IS_WSGI=False
      - PORT=8000
    depends_on:
      - db
      - mjml

  backend-migration:
    image: baserow_backend
    command: python src/baserow/manage.py migrate --noinput
    environment:
      - POSTGRES_USER=baserow
      - POSTGRES_PASSWORD=baserow
      - POSTGRES_DB=baserow
      - DATABASE_PORT=5432
      - IS_WSGI=False
      - PORT=8000
    volumes:
      - ./backend:/usr/src/backend
    depends_on:
      - db
      - backend

  web-frontend:
    container_name: web-frontend
    build:
      context: ./web-frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./web-frontend:/usr/src/web-frontend
      - /usr/src/web-frontend/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend

networks:
  default:
    external:
      name: baserow_default
