version: "3"

services:

  backend:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile.dev
      args:
        # We allow configuring the UID/GID here so you can run as the dev's actual user
        # reducing the chance the containers screw up the bind mounted folders.
        UID: "${UID:-}"
        GID: "${GID:-}"
    image: baserow_backend_dev:latest
    volumes:
      - ./backend:/baserow/backend
      - ./premium/backend/:/baserow/backend/plugins/premium
      - backend-dev-plugins:/baserow/backend/plugins
    # Open stdin and tty so when attaching key input works as expected.
    stdin_open: true
    tty: true

  celery:
    image: baserow_backend_dev:latest
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile.dev
      args:
        # We allow configuring the UID/GID here so you can run as the dev's actual user
        # reducing the chance the containers screw up the bind mounted folders.
        UID: "${UID:-}"
        GID: "${GID:-}"
    command: celery-dev
    volumes:
      - ./backend:/baserow/backend
      - ./premium/backend/:/baserow/backend/plugins/premium
      - backend-dev-plugins:/baserow/backend/plugins
    # Open stdin and tty so when attaching key input works as expected.
    stdin_open: true
    tty: true

  web-frontend:
    build:
      context: .
      dockerfile: ./web-frontend/docker/Dockerfile.dev
      args:
        # We allow configuring the UID/GID here so you can run as the dev's actual user
        # reducing the chance the containers screw up the bind mounted folders.
        UID: "${UID:-}"
        GID: "${GID:-}"
    image: baserow_web-frontend_dev:latest
    volumes:
      - ./web-frontend:/baserow/web-frontend
      - ./premium/web-frontend/:/baserow/web-frontend/plugins/premium
      - web-frontend-dev-node-modules:/baserow/web-frontend/node_modules
      - web-frontend-dev-plugins:/baserow/web-frontend/plugins

    # Open stdin and tty so when attaching key input works as expected.
    stdin_open: true
    tty: true

  media-volume-fixer:
    command: chown ${UID:-1000}:${GID:-1000} -R /baserow/media

# Give names to the volumes declared in the docker dev images so we dont end up with hundreds
# of anonymous volumes.
volumes:
  web-frontend-dev-node-modules:
  web-frontend-dev-plugins:
  backend-dev-plugins: