version: "3"

services:
  db:
    image: postgres:11.3
    environment:
      - POSTGRES_USER=baserow
      - POSTGRES_PASSWORD=baserow
      - POSTGRES_DB=baserow
    ports:
      - 5432:5432

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    depends_on:
      - db

  web-frontend:
    container_name: web-frontend
    build:
      context: ./web-frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./web-frontend:/web-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
