version: "3"

services:
  db:
    container_name: baserow-demo-db
    image: postgres:11.3
    environment:
      - POSTGRES_USER=baserow
      - POSTGRES_PASSWORD=baserow
      - POSTGRES_DB=baserow
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:6.0
    ports:
      - 6379:6379

  mjml:
    container_name: baserow-demo-mjml
    image: liminspace/mjml-tcpserver:latest
    ports:
      - 28101:28101

  backend:
    container_name: baserow-demo-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.demo
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - mjml

  web-frontend:
    container_name: baserow-demo-web-frontend
    build:
      context: ./web-frontend/
      dockerfile: Dockerfile.demo
    ports:
      - 3000:3000
    depends_on:
      - backend

networks:
  default:
    external:
      name: baserow_demo_default
