---

title: Job scheduling and executing
---

flowchart LR

    frontend --> |calls job-type specific endpoint| job_creation_api
    job_creation_api --> |writes job details to job tables| db
    job_creation_api --> |schedules a task| celery
    celery --> |runs a task| run_async_task
    db --> |gets job details| run_async_task
    run_async_task --> |executes| job

    subgraph frontend_box[Frontend]
        frontend[Component]
    end
    subgraph backend_box[Backend]
        job_creation_api[Job creation endpoint]
    end
    subgraph celery_box[Celery]
        celery
        run_async_task
        job
    end
    subgraph db_box[DB]
        db
    end


    %%cache -...-> |checks for cancellation| job
    %%frontend -...-> | cancels a job| backend
    %%backend -...-> | sets cancellation state | cache
    %%job -...-> |writes cancellation state| db

    %%job ==> |updates status & progress| cache
    %%job ==> |writes the final status| db
    %%db ==> | checks current state & progress| backend
    %%backend ==> | checks current state & progress| frontend

    %% job scheduling path
    linkStyle 0,1,2,3,4,5 stroke:#271,stroke-width:3px;
    %% job cancellation path
    %%linkStyle 6,7,8,9 stroke:#f45,stroke-width:3px;
    %% job execution
    %%linkStyle 4,5,10,11 stroke:#2f3,stroke-width:4px;
    %% job status update
    %%linkStyle 12,13 stroke:#23e,stroke-width:4px;
