---

title: Job status check
---

flowchart LR

    frontend --> |calls job status endpoint| job_status_api
    db --> |read job status| job_status_api
    cache ==> |updates status & progress| job
    db ==> |writes the final status| job
    run_async_task ==> |runs| job
    cache ==> |reads job status| job_status_api

    subgraph frontend_box[Frontend]
        frontend[Component]
    end

    subgraph backend_box[Backend]
        job_creation_api[Job creation endpoint]
        job_status_api[Job status endpoint]
    end
     subgraph celery_box[Celery]
        run_async_task
        job
    end

    subgraph db_box[DB]
        db
    end


    %%cache -...-> |checks for cancellation| job
    %%frontend -...-> | cancels a job| backend
    %%backend -...-> | sets cancellation state | cache
    %%job -...-> |writes cancellation state| db

    %%job ==> |updates status & progress| cache
    %%job ==> |writes the final status| db
    %%db ==> | checks current state & progress| backend
    %%backend ==> | checks current state & progress| frontend

    %% job scheduling path
    linkStyle 0,1 stroke:#3e6,stroke-width:3px;
    %% job cancellation path
    %%linkStyle 6,7,8,9 stroke:#f45,stroke-width:3px;
    %% job execution
    %%linkStyle 4,5,10,11 stroke:#2f3,stroke-width:4px;
    %% job status update
    %%linkStyle 12,13 stroke:#23e,stroke-width:4px;
