# Generated by Django 5.0.9 on 2024-10-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0039_alter_page_options_page_shared"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiPageContainerElement",
            fields=[
                (
                    "element_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.element",
                    ),
                ),
                (
                    "page_position",
                    models.CharField(
                        choices=[
                            ("header", "Header"),
                            ("footer", "Footer"),
                            ("left", "Left"),
                            ("right", "Right"),
                        ],
                        default="header",
                        max_length=10,
                    ),
                ),
                (
                    "behaviour",
                    models.CharField(
                        choices=[
                            ("scroll", "Scroll"),
                            ("fixed", "Fixed"),
                            ("sticky", "Sticky"),
                        ],
                        default="scroll",
                        max_length=10,
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("only", "Only"),
                            ("except", "Except"),
                        ],
                        default="all",
                        max_length=12,
                    ),
                ),
                ("pages", models.ManyToManyField(blank=True, to="builder.page")),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.element",),
        ),
    ]
