# Generated by Django 5.0.9 on 2024-09-30 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0039_alter_page_options_page_shared"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="builderworkflowaction",
            options={"ordering": ("order", "id")},
        ),
    ]
