# Generated by Django 3.2.18 on 2023-03-29 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0068_connection"),
        ("database", "0111_alter_airtableimportjob_workspace"),
        ("automation", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaserowConnection",
            fields=[
                (
                    "connection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.connection",
                    ),
                ),
            ],
            bases=("core.connection",),
        ),
        migrations.CreateModel(
            name="BaserowRowCreatedTrigger",
            fields=[
                (
                    "trigger_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="automation.trigger",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baserow_row_created_triggers",
                        to="database.table",
                    ),
                ),
            ],
            bases=("automation.trigger",),
        ),
    ]
