# Generated by Django 3.2.18 on 2023-03-29 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0068_connection"),
        ("baserow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalBaserowConnection",
            fields=[
                (
                    "connection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.connection",
                    ),
                ),
                ("api_key", models.CharField(max_length=255)),
                ("baserow_url", models.URLField()),
            ],
            bases=("core.connection",),
        ),
        migrations.CreateModel(
            name="InternalBaserowConnection",
            fields=[
                (
                    "connection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.connection",
                    ),
                ),
                (
                    "authorized_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("core.connection",),
        ),
        migrations.DeleteModel(
            name="BaserowConnection",
        ),
    ]
