# Generated by Django 3.2.18 on 2023-04-04 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_useraction'),
        ('database', '0111_alter_airtableimportjob_workspace'),
        ('baserow', '0002_auto_20230329_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaserowListRowsUserAction',
            fields=[
                ('useraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.useraction')),
                ('table', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baserow_list_rows_user_actions', to='database.table')),
            ],
            bases=('automation.useraction',),
        ),
    ]
