# Generated by Django 3.2.18 on 2023-04-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_auto_20230404_2005'),
        ('database', '0111_alter_airtableimportjob_workspace'),
        ('baserow', '0003_baserowlistrowsuseraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaserowGetRowUserAction',
            fields=[
                ('useraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.useraction')),
                ('row_id', models.IntegerField(default=None, null=True)),
                ('table', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baserow_get_row_user_actions', to='database.table')),
            ],
            bases=('automation.useraction',),
        ),
    ]
