# Generated by Django 3.2.18 on 2023-03-29 19:02

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0067_alter_settings_track_workspace_usage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Automation",
            fields=[
                (
                    "application_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.application",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.application",),
        ),
        migrations.CreateModel(
            name="Trigger",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            bases=(baserow.core.mixins.PolymorphicContentTypeMixin, models.Model),
        ),
    ]
