# Generated by Django 3.2.18 on 2023-03-29 19:02

import django.db.models.deletion
from django.db import migrations, models

import baserow.contrib.automation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0068_connection"),
        ("automation", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="connection",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="automation_triggers",
                to="core.connection",
                verbose_name="connection",
            ),
        ),
        migrations.AddField(
            model_name="trigger",
            name="content_type",
            field=models.ForeignKey(
                on_delete=models.SET(
                    baserow.contrib.automation.models.get_default_trigger_content_type
                ),
                related_name="automation_triggers",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AddField(
            model_name="automation",
            name="trigger",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="automation.trigger",
            ),
        ),
    ]
