# Generated by Django 3.2.18 on 2023-03-29 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_alter_automation_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automation",
            name="trigger",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="automations",
                to="automation.trigger",
            ),
        ),
    ]
