# Generated by Django 3.2.18 on 2023-03-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0006_automationrun"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automationrun",
            name="status",
        ),
        migrations.AddField(
            model_name="automationrun",
            name="failed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="automationrun",
            name="failed_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="automationrun",
            name="finished_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="automationrun",
            name="trigger_payload",
            field=models.JSONField(default={}),
        ),
    ]
