# Generated by Django 3.2.18 on 2023-03-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0007_auto_20230329_2138"),
    ]

    operations = [
        migrations.RenameField(
            model_name="automationrun",
            old_name="finished_at",
            new_name="completed_at",
        ),
        migrations.AlterField(
            model_name="automationrun",
            name="trigger_payload",
            field=models.JSONField(null=True),
        ),
    ]
