# Generated by Django 3.2.18 on 2023-04-04 19:42

import baserow.contrib.automation.models
import baserow.core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_connection'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('automation', '0008_auto_20230329_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='automation.automation', verbose_name='content type')),
                ('connection', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_user_actions', to='core.connection', verbose_name='connection')),
                ('content_type', models.ForeignKey(on_delete=models.SET(baserow.contrib.automation.models.get_default_trigger_content_type), related_name='automation_user_actions', to='contenttypes.contenttype', verbose_name='content type')),
            ],
            bases=(baserow.core.mixins.PolymorphicContentTypeMixin, models.Model),
        ),
    ]
