# Generated by Django 3.2.18 on 2023-04-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_useraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='automation.useraction', verbose_name='parents'),
        ),
        migrations.CreateModel(
            name='AutomationRunUserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_payload', models.JSONField(null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_run_user_actions', to='automation.useraction', verbose_name='user action')),
                ('automation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='automation.automationrun', verbose_name='automation run')),
            ],
        ),
    ]
