# Generated by Django 2.2.11 on 2021-01-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20210105_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='calls',
            field=models.IntegerField(default=0),
        ),
    ]
