# Generated by Django 2.2.11 on 2021-01-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20210105_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='calls',
            new_name='call_count',
        ),
    ]
