# Generated by Django 2.2.11 on 2021-06-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_fix_url_field_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
