# Generated by Django 2.2.11 on 2021-07-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_form_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastModifiedField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.Field')),
                ('date_format', models.CharField(choices=[('EU', 'European (D/M/Y)'), ('US', 'US (M/D/Y)'), ('ISO', 'ISO (Y-M-D)')], default='EU', help_text='EU (20/02/2020), US (02/20/2020) or ISO (2020-02-20)', max_length=32)),
                ('date_include_time', models.BooleanField(default=False, help_text='Indicates if the field also includes a time.')),
                ('date_time_format', models.CharField(choices=[('24', '24 hour'), ('12', '12 hour')], default='24', help_text='24 (14:30) or 12 (02:30 PM)', max_length=32)),
            ],
            options={
                'abstract': False,
            },
            bases=('database.field', models.Model),
        ),
    ]
