# Generated by Django 4.2.13 on 2024-09-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0164_datasync_field_read_only_icalcalendardatasync_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasyncproperty",
            name="data_sync",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_sync_properties",
                to="database.datasync",
            ),
        ),
        migrations.AlterField(
            model_name="icalcalendardatasync",
            name="ical_url",
            field=models.URLField(max_length=2000),
        ),
    ]
