# Generated by Django 5.0.9 on 2024-10-09 13:10

import typing

from django.db import migrations

if typing.TYPE_CHECKING:
    from celery import Task


def schedule_tsv_update(task: "Task", table_id: int, fields: list):
    if not table_id or not fields:
        return
    task.delay(
        table_id=table_id,
        update_tsvs_for_changed_rows_only=False,
        field_ids_to_restrict_update_to=fields,
    )


def update_password_tsv_index(apps, schema_editor):
    PasswordField = apps.get_model("database", "PasswordField")
    from baserow.contrib.database.search.tasks import async_update_tsvector_columns

    current_table = None
    current_fields = None
    for table_id, field_id in PasswordField.objects.values_list(
        "table_id", "id"
    ).order_by("table_id", "id"):
        if current_table != table_id:
            schedule_tsv_update(
                async_update_tsvector_columns, current_table, current_fields
            )
            current_table = table_id
            current_fields = []
        current_fields.append(field_id)

    schedule_tsv_update(async_update_tsvector_columns, current_table, current_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0169_alter_galleryview_card_cover_image_field"),
    ]

    operations = [migrations.RunPython(update_password_tsv_index)]
