# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision :shell, path: "bootstrap.sh", :args=>"https://gitlab.com/bramw/baserow.git 385-add-mjml-installation-instructions-in-the-ubuntu-installation-tutorial"
  config.vm.network :forwarded_port, guest: 3000, host: 3000, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 4000, host: 4000, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 8000, host: 8000, host_ip: "127.0.0.1"
  # Prevent TTY Errors (copied from laravel/homestead: "homestead.rb" file)... By default this is "bash -l".
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
end
