# Generated by Django 5.0.9 on 2024-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0010_localbaserowaggregaterows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localbaserowaggregaterows",
            name="search_query",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The query to apply to the service to narrow the results down.",
                max_length=225,
            ),
        ),
    ]
