# Generated by Django 2.2.11 on 2021-07-06 13:26

from django.db import migrations


def forward(apps, schema_editor):
    """
    Add missing Profile to existing users.
    """
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("core", "UserProfile")
    for user in User.objects.all():
        UserProfile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_user_profile"),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
