# Generated by Django 3.2.18 on 2023-03-29 19:02

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.mixins
import baserow.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0067_alter_settings_track_workspace_usage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="core.application",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=models.SET(
                            baserow.core.models.get_default_connection
                        ),
                        related_name="connections",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
            ],
            bases=(baserow.core.mixins.PolymorphicContentTypeMixin, models.Model),
        ),
    ]
