# Generated by Django 5.0.9 on 2024-10-17 06:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0090_exportapplicationsjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportApplicationsJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.job",
                    ),
                ),
                (
                    "user_ip_address",
                    models.GenericIPAddressField(
                        help_text="The user IP address.", null=True
                    ),
                ),
                (
                    "user_websocket_id",
                    models.CharField(
                        help_text="The user websocket uuid needed to manage signals sent correctly.",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "user_session_id",
                    models.CharField(
                        help_text="The user session uuid needed for undo/redo functionality.",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "user_action_group_id",
                    models.CharField(
                        help_text="The user session uuid needed for undo/redo action group functionality.",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "workspace_id",
                    models.PositiveIntegerField(
                        help_text="The workspace id that the applications are going to be imported to."
                    ),
                ),
                (
                    "file_name",
                    models.TextField(help_text="Name of import file in storage."),
                ),
                (
                    "only_structure",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if only the structure of the applications should be exported, without user data.",
                    ),
                ),
                (
                    "application_ids",
                    models.TextField(
                        help_text="The comma separated list of application ids that have been created by the import."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.job", models.Model),
        ),
        migrations.CreateModel(
            name="ImportResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "workspace_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="The workspace id that the applications are going to be imported to.",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
